global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'event-service'
    static_configs:
      - targets: ['event-service:8000']
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
